services:
  webtoon-server:
    image: ghcr.io/murianwind/webtoon-server:latest
    container_name: webtoon-server
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "25600:8000"
    environment:
      - "TZ=Asia/Seoul"
      - "PUBLIC_BASE_URL=https://komga.murian.ddnsfree.com"
      - "RESCAN_INTERVAL_SECONDS=7200"
    volumes:
      - "D:/Webtoon/네이버 웹툰:/library/네이버"
      - "D:/Webtoon/카카오 웹툰:/library/카카오"
      - "webtoon_onedrive:/library/원드라이브:ro"
      - "webtoon_data:/data"
    restart: unless-stopped

volumes:
  webtoon_data:
  webtoon_onedrive:
    external: true
